[package]
name = "aoc-2017"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nog = "0.1.0"
simplelog = "0.12.1"
